version: '3'

services:
    php:
        image: akeneo/php:7.2
        environment:
            COMPOSER_HOME: /home/docker/.composer
            PHP_IDE_CONFIG: 'serverName=docker'
            PHP_XDEBUG_ENABLED: "${PHP_XDEBUG_ENABLED}"
            PHP_XDEBUG_IDE_KEY: XDEBUG_IDE_KEY
            XDEBUG_CONFIG: 'remote_host=${DOCKER_HOST_IP}'
        user: docker
        volumes:
            - ./:/home/docker/
        working_dir: /home/docker/

    mysql:
        image: 'akeneo-training-sql/mysql:5.7'
        build:
            context: docker/mysql
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
        networks:
            - training
        ports:
            - '${MYSQL_EXPOSED_PORT}:3306'

networks:
    training:
